name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from
    
  # Enable manual deployment from GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
        
      - name: List files in directory
        run: ls -la
      
      - name: Build website
        run: |
          echo "Starting build..."
          npm run build || (echo "Build failed with code $?" && ls -la && exit 1)
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
