name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from
    
  # Enable manual deployment from GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Setup .env file if needed
        run: |
          echo "NODE_ENV=production" > .env
          echo "NEXT_PUBLIC_BASE_PATH=/nichevendor" >> .env
      
      - name: List files in directory
        run: ls -la
      
      - name: Clean dynamic route directories
        run: |
          rm -rf app/orders/[id]
          mkdir -p app/orders/sample-order-1
          mkdir -p app/orders/sample-order-2
          mkdir -p app/orders/sample-order-1/edit
          mkdir -p app/orders/sample-order-2/edit
      
      - name: Build website
        run: |
          echo "Starting build..."
          npm run build || { 
            echo "Build failed with code $?"
            echo "Package.json contents:"
            cat package.json
            echo "Next.config.js contents:"
            cat next.config.js
            echo "Directory contents:"
            ls -la
            exit 1
          }
          echo "Build completed, touching .nojekyll file"
          touch out/.nojekyll
          
          # Copy our custom index.html to the build output
          echo "Copying custom index.html to build output"
          cp index.html out/index.html
          
          # Ensure mobile fixes are included in the output
          echo "Copying mobile fix files to output"
          mkdir -p out/mobile-fixes
          cp public/mobile-fixes.css out/mobile-fixes.css
          cp public/mobile-fixes.js out/mobile-fixes.js
          
          echo "Listing output directory:"
          ls -la out/
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
      
      - name: Print GitHub Pages instructions
        run: |
          echo "======================================"
          echo "DEPLOYMENT COMPLETE"
          echo "======================================"
          echo "Please ensure GitHub Pages is configured properly:"
          echo "1. Go to your repository Settings"
          echo "2. Select 'Pages' from the left menu"
          echo "3. Make sure 'Source' is set to 'Deploy from a branch'"
          echo "4. Set the branch to 'gh-pages' with folder set to '/ (root)'"
          echo "5. After saving, wait a few minutes for the deployment to complete"
          echo "6. Your site should be available at https://rocketmobster.github.io/nichevendor/"
          echo "======================================"
